Индивидуальное задание (вариант 5):

Дана целочисленная квадратная матрица. Определить:
- сумму элементов в тех столбцах, которые не содержат отрицательных элементов;
- минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали матрицы.

In [12]:
import numpy as np

k = int(input("Введите размерность матрицы: "))
matrix =  np.random.randint(-10, 20, size=(k, k))

Введите размерность матрицы: 5


In [13]:
print("Матрица:\n", matrix)

Матрица:
 [[  9  -9   0  12   0]
 [ 11  14  -6 -10  -7]
 [  8  11  -7  11   2]
 [ 10   8  13  -2  12]
 [  9  13  15  12  12]]


In [29]:
print("Столбцы, не содержащие отрицательные элементы:\n", matrix[:, matrix.min(axis=0) > 0])

Столбцы, не содержащие отрицательные элементы:
 [[ 9]
 [11]
 [ 8]
 [10]
 [ 9]]


In [31]:
sumP = np.sum(matrix[:, matrix.min(axis=0) > 0])
print("Сумма элементов в столбцах, которые не содержат отрицательные элементы:", sumP)

Сумма элементов в столбцах, которые не содержат отрицательные элементы: 47


In [63]:
mod = np.fliplr(np.absolute(matrix))
print("Отзеркаленная матрица модулей элементов\n", mod)

Отзеркаленная матрица модулей элементов
 [[ 0 12  0  9  9]
 [ 7 10  6 14 11]
 [ 2 11  7 11  8]
 [12  2 13  8 10]
 [12 12 15 13  9]]


In [78]:
a = min([mod.trace(offset=i) for i in np.arange(1-k, k)])
print("Mинимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали матрицы: ", a)

Mинимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали матрицы:  9
